#挂号记录表1
ALTER TABLE BIZ_REGISTER_RECORD_1 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_1 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表2
ALTER TABLE BIZ_REGISTER_RECORD_2 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_2 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表3
ALTER TABLE BIZ_REGISTER_RECORD_3 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_3 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表4
ALTER TABLE BIZ_REGISTER_RECORD_4 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_4 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表5
ALTER TABLE BIZ_REGISTER_RECORD_5 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_5 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表6
ALTER TABLE BIZ_REGISTER_RECORD_6 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_6 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表7
ALTER TABLE BIZ_REGISTER_RECORD_7 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_7 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表8
ALTER TABLE BIZ_REGISTER_RECORD_8 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_8 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表9
ALTER TABLE BIZ_REGISTER_RECORD_9 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_9 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#挂号记录表10
ALTER TABLE BIZ_REGISTER_RECORD_10 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_REGISTER_RECORD_10 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表1
ALTER TABLE BIZ_CLINIC_RECORD_1 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_1 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表2
ALTER TABLE BIZ_CLINIC_RECORD_2 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_2 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表3
ALTER TABLE BIZ_CLINIC_RECORD_3 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_3 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表4
ALTER TABLE BIZ_CLINIC_RECORD_4 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_4 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表5
ALTER TABLE BIZ_CLINIC_RECORD_5 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_5 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表6
ALTER TABLE BIZ_CLINIC_RECORD_6 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_6 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表7
ALTER TABLE BIZ_CLINIC_RECORD_7 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_7 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表8
ALTER TABLE BIZ_CLINIC_RECORD_8 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_8 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表9
ALTER TABLE BIZ_CLINIC_RECORD_9 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_9 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';

#门诊记录表10
ALTER TABLE BIZ_CLINIC_RECORD_10 ADD COLUMN CANCEL_SERIAL_NO VARCHAR(100) COMMENT '退款流水号';
ALTER TABLE BIZ_CLINIC_RECORD_10 ADD COLUMN CANCEL_BILL_NO VARCHAR(100) COMMENT '退款单据号';
